language: php
php:
- 5.4
before_script:
  - composer install
  - chmod -Rf 777 app/cache
  - chmod -Rf 777 app/logs
  - mv app/config/parameters.yml.dist parameters.yml
  - php app/console doctrine:database:create
  - mysql -uroot symfony < blog_structure.sql
script: phpunit -c app --codecoverage
