topic:
    type: rest
    prefix: /api
    resource:   ridesoft\TopicsApiBundle\Controller\TopicController

article:
    type: rest
    prefix: /api
    resource:   ridesoft\TopicsApiBundle\Controller\ArticleController
